### ISSUE TITLE
Do you have plans to support Chinese, French, German specific character?

### ISSUE THREAD

**Issue by fedorinoGore** [RandomMaerks/Overused-Grotesk#13]
Would be great to have a font that supports many languages.

**Comment by RandomMaerks** [comment]
I believe the current version supports French and German, along with some regional variants of those languages.

There is also no plans for Chinese support, due to the lack of resources and understanding coming from me as a non-Chinese speaker. Unless someone is willing to contribute, I doubt the fonts would be having Chinese characters anytime soon.
