### ISSUE TITLE
Kerning A & T characters

### ISSUE THREAD

**Issue by amazingnerd** [RandomMaerks/Overused-Grotesk#8]
Hello,
There're an spacing between A and T that need to kern. How do you think about that?
<img width="628" alt="image" src="https://github.com/RandomMaerks/Overused-Grotesk/assets/87475722/2425f92c-f33f-4a15-a2a2-e9f7a868a770">

**Comment by RandomMaerks** [comment]
Are you using an older version (before v0.4)? I don't see the problem here.

![image](https://github.com/RandomMaerks/Overused-Grotesk/assets/109415614/704d8b20-d8a3-48bd-9682-82189481b0d2)

I've tested the latest release (v0.4) and the most recent source, the kerning is present in all of the fonts.

It also seems that CA and RY pairs aren't kerned yet. Did you enable kerning on the program you're using?

**Comment by RandomMaerks** [comment]
I think I see the problem. That spur from the letter 'G' looks oddly different from the current version. You might have been using an old version mate

**Comment by amazingnerd** [comment]
I'll try to use the newest version, thank you mate
